# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Image_Name', models.CharField(max_length=60)),
                ('Image_Caption', models.CharField(max_length=60)),
                ('Likes', models.CharField(max_length=10)),
                ('Comments', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ImageField(upload_to='images/')),
                ('Bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.Profile'),
        ),
    ]
