# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_image_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='User_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
